spring:
  # Application
  application:
    name: gateway-service
server:
  port: 8080
# Eureka service registry
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka