spring:
  application:
    name: eureka-discovery-service
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka