spring:
  # Database
  datasource:
    url: ${POSTGRES_DB_PATH}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # Application
  application:
    name: location-service
server:
  port: 8084
# Eureka service registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka